global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["localhost:9100"]

remote_write:
  - url: "http://100.80.185.40:3000"
    basic_auth:
      username: "admin"
      password: "<password>"

  - url: "http://91.170.61.8:3000"
    basic_auth:
      username: "admin"
      password: ""
